### ISSUE TITLE
particle demo

### ISSUE THREAD

**Issue by arcanosam** [cptx032/lightk#1]
Hi!

I looking for this demo you made: https://youtu.be/Xj0yqEJpjVw

I ran every project, none it is this demo.

Could you update your repo with him?

Great code! thanks for sharing!

Samuel

p.s.: I'm from Brazil, are you too?

**Comment by cptx032** [comment]
Opa, obrigado!
Eu realmente esqueci desses exemplos o.O
sou brasileiro! :)

**Comment by arcanosam** [comment]
valeu manow!
tu soube extrair muito legal o poder do Tkinter! são ótimos exemplos para aprofundar!
